version: '3.7'
services:
  wordpress:
    image: wordpress:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: sua_senha
      WORDPRESS_DB_NAME: wordpress1
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', false);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_HOME', 'http://10.83.0.9');
        define('WP_SITEURL', 'http://10.83.0.9');
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mysql
    networks:
      - app_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  mysql:
    image: mysql:8.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    environment:
      MYSQL_ROOT_PASSWORD: sua_senha
      MYSQL_DATABASE: wordpress1
      MYSQL_USER: root
      MYSQL_PASSWORD: sua_senha
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  wordpress_data:
    name: wordpress_data
  mysql_data:
    name: mysql_data
networks:
  app_net:
    driver: overlay
    attachable: true
